<!DOCTYPE html>
<html lang="fr">

<head>
    <link rel="stylesheet" href="./css/texte_image.css">
    <link rel="stylesheet" href="../entete/header.css">

    <?php
    include("../entete/link.php");
    ?>



    <!-- Balises de referencements -->
    <meta name="description" content="Portfolio personnel de Sinclair Moulager afin de présenter ses compétences et acquis pour la vie profesionnelle.">
    <meta name="keywords" content="portfolio , cv , presentation , compétences , developpeur , developpeur-web , informatique">
    <meta name="robots" content="index,follow">
    <title>Sinclair Moulager | Portfolio</title>
</head>

<body>
    <?php
    include("../entete/header.php");
    ?>
    <main>
        <section>
            <div class="div-text">
            <h5>L'incrustation !! </h5>
            <lord-icon src="https://cdn.lordicon.com/xaubpxfc.json" trigger="hover" style="width:25px;height:25px">
            </lord-icon>
            </div>

            <div>
                <div class="image-texted">
                    <p>
                    LAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOWLAIDLOW
                    </p>
                </div>
            </div>
            <div class="div-text mt-5">
                <p>Mais qui cela peut-il bien être ?</p>
            </div>
        </section>
    </main>
</body>